### ISSUE TITLE
php version bump

### ISSUE THREAD

**Issue by KJLJon** [starekrow/lockbox#18]
I see you bumped the version to php 7 because of phpunit.  I quick tested and it looks like I can get phpunit 4.x running with 2 minor changes to the tests (which supports php 5.5).

Although, I still like the idea of supporting 7+ (or 5.6+) because of PHP security patching support, but I also think the version shouldn't be bumped just because of the testing framework.

PHP support: http://php.net/supported-versions.php

see https://github.com/KJLJon/lockbox/commit/d8be02677d6d763619a52aa00a9fa09edb9e3d53 for 5.5+ fix.

@starekrow what are your thoughts?  I can send a PR for the commit listed above if you still want to support php 5.5+

**Comment by starekrow** [comment]
The bump to 7 was indeed supposed to be temporary, I only had a few minutes to get Travis up and running. However, that got me thinking that it’s been a few years since I did a proper survey of PHP versions in use at various levels/types of hosting. My sense is that 5.6 and even 5.5 are still seeing an amount of use in production, in which case we should definitely support them. I’d be interested in your thoughts as well, and I’ll take a look around the net tomorrow.

**Comment by KJLJon** [comment]
Without doing much research on market adoption of php versions.

I think 5.5+ is a good place to start.  If people start wanting to use this package with earlier versions (php5.3+) it could be addressed at that time (with some polyfills where needed).  It might even work already with php5.3 (I would need to look up all the php functions on php.net to see if any aren't supported).

I think it is more of a commitment question on how much work is needed to maintain the older versions vs market adoption.

**Comment by KJLJon** [comment]
ill submit a pr for php 5.5.  Feel free to merge, or ask me to update it to any other min version you would like to support, and I can update it :-)
