### ISSUE TITLE
PHPDoc

### ISSUE THREAD

**Issue by KJLJon** [starekrow/lockbox#7]
Change comments format to phpdoc for better IDE support :)
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md

**Comment by starekrow** [comment]
Gah. I used to love javadoc, but it turned out that was only because SlickEdit had utterly amazing support for it. Haven't found the right package for Sublime Text yet, and without editor support that format is a horrible PITA to work with, with a comparatively small payoff.

That said, if anyone else is actually going to be using this code I'm not opposed to the change.

**Comment by alexmanno** [comment]
I guys, I think that to make this library better you have to use the standard PhpDoc, I opened a PR to solve this

**Comment by starekrow** [comment]
Done in PR #14
